name: Build, attest, release

on:
  workflow_dispatch:    

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      attestations: write

    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Prepare java
        uses: actions/setup-java@3a4f6e1af504cf6a31855fa899c6aa5355ba6c12 # v4.7.0
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Install clojure tools
        uses: DeLaGuardo/setup-clojure@cc67f8308550d0f18b0ba445c2476f84626a5d6a # 13.1
        with:
          # Install just one or all simultaneously
          cli: 1.12.0.1517 # Clojure CLI based on tools.deps
          cljfmt: 0.13.0
      - name: Cache clojure dependencies
        uses: actions/cache@1bd1e32a3bdc45362d1e726936510720a7c30a57 # v4.2.0
        with:
          path: |
            ~/.m2/repository
            ~/.gitlibs
            ~/.deps.clj
          # List all files containing dependencies:
          key: cljdeps-${{ hashFiles('deps.edn') }}
          # key: cljdeps-${{ hashFiles('deps.edn', 'bb.edn') }}
          # key: cljdeps-${{ hashFiles('project.clj') }}
          # key: cljdeps-${{ hashFiles('build.boot') }}
          restore-keys: cljdeps-
      - name: Build artifact
        run: |
            clojure -T:build jar
            cp target/classes/META-INF/maven/clojupyter/clojupyter/pom.xml ./
            echo "TARGET_JAR=$(find target/clojupyter-*.jar)" >> $GITHUB_ENV

      - name: Attest
        uses: actions/attest-build-provenance@v2
        with:
          subject-path: '${{ github.workspace }}/${{ env.TARGET_JAR }}'
      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v4
        with:
          name: jar
          path: '${{ github.workspace }}/${{ env.TARGET_JAR }}'
          retention-days: 5
